/** Auto-generated CAN message definitions from DBC file. */

#include "can_nerve.h"

const can_message_t dbc_messages[] = {
    {
        .name = "state",
        .message_id = 257,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "state",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "barometric",
        .message_id = 258,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "pressure",
                    .start_bit = 0,
                    .bit_length = 24,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 0.00566f,
                    .offset = 30000.0f,
                    .min_value = 30000.0f,
                    .max_value = 124959.0369f,
                },
                {
                    .name = "temperature",
                    .start_bit = 24,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 0.0019074f,
                    .offset = -40.0f,
                    .min_value = -40.0f,
                    .max_value = 85.001459f,
                },
                {
                    .name = "state",
                    .start_bit = 40,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "gps1",
        .message_id = 259,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "latitude",
                    .start_bit = 0,
                    .bit_length = 30,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "lat_dir",
                    .start_bit = 30,
                    .bit_length = 2,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "longitude",
                    .start_bit = 32,
                    .bit_length = 30,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "long_dir",
                    .start_bit = 62,
                    .bit_length = 2,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "gps2",
        .message_id = 260,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 5,
        .signals =
            {
                {
                    .name = "altitude",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "horizontalSpeed",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "verticalSpeed",
                    .start_bit = 32,
                    .bit_length = 12,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "heading",
                    .start_bit = 44,
                    .bit_length = 12,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "status",
                    .start_bit = 56,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "gps3",
        .message_id = 261,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "gnss_fix_type",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "satellite_count",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "timestamp",
                    .start_bit = 16,
                    .bit_length = 32,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "imu1",
        .message_id = 262,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "quaternion_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "quaternion_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "quaternion_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "quaternion_w",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "imu2",
        .message_id = 263,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "gyro_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "gyro_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "gyro_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "imu3",
        .message_id = 264,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "accel_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "accel_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "accel_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "imu4",
        .message_id = 265,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "lin_accel_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "lin_accel_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "lin_accel_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
    {
        .name = "imu5",
        .message_id = 272,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "gravity_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "gravity_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
                {
                    .name = "gravity_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 0.0f,
                },
            },
    },
};

const int dbc_message_count = sizeof(dbc_messages) / sizeof(dbc_messages[0]);
